name: Portfolio CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: flyluman/portfolio
      PORT: 8080
      QUERY_PASS: __really!?
      NODE_ENV: production

    steps:

      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up NodeJS
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '23'
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm i

      # Step 4: Run the app
      - name: Run the app
        run: |
          node server.js &
          sleep 5 # Server bootup time
      
      # Step 5: Test a route
      - name: Test a route
        run: curl localhost:8080/Test


      


